// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package database

import ()

type Todo struct {
	ID        int32
	Name      string
	Completed bool
	UserID    int32
}

type User struct {
	ID       int32
	Username string
	Password string
}
